---
title: "EEPA, CF"
subtitle: ""
author: 
  - Ozan Jaquette
  - Karina Salazar
bibliography: ../bib/eepa_student_list.bib
citeproc: no
output: 
  #bookdown::word_document2:    
  bookdown::pdf_document2:
    toc: FALSE
    pandoc_args: !expr rmdfiltr::add_wordcount_filter(rmdfiltr::add_citeproc_filter(args = NULL))
eoutput: pdf_document
always_allow_html: true
csl: ../bib/apa.csl
urlcolor: blue
fontsize: 12pt
#header-includes:
#      - \usepackage{pdflscape}
#      - \usepackage{geometry}
header-includes:
      - \usepackage{floatrow}
      - \floatsetup{capposition=top}
      - \usepackage{setspace}\onehalfspacing #\doublespacing
---



## Capital

_**Marx, Capital**_. Following, @RN4799 we conceptualize student list data as a form of capital. First, we introduce basic concepts. In _Capital_, @RN1423 describes the process by which capitalists invest money ($M$) to generate profit. A _commodity_ is an object that has both _use-value_ – the practical utility of an object – and _exchange-value_ – what the object can be exchanged for, usually measured in terms of money. The formula $C-M$ -- commodity for money -- represents a sale and the formula $M-C$ -- money for a commodity represents a purchase. 

@RN1423 distinguishes between two fundamental cycles between money and commodities. First, $C-M-C'$ is the formula for _consumption_; a commodity $C$ is sold for money $M$, which is then used to purchase another commodity $C'$. Here, the end goal is the use-value of commodity $C'$. The consumption transaction generates no profit -- because the exchange value of commodity $C$ is the same as the exchange-value of commodity $C'$ -- and at the end of this transaction the money $M$ ceases to be capital because it is expended.

Second, the formula $M-C-M'$ represents capital. Here, money $M$ is used to buy a commodity $C$, which is sold for money $M'$. In the formula for capital, $M'$ exceeds $M$, such that capitalists generate a "surplus value" or profit of $M' -M$. [@RN4799, p. 4] describes the "logic of capital accumulation

> this unending accumulation of capital, represented by $M-C-M'-C-M''-C-M''' \ldots$, is a defining feature of capitalism. \ldots, As Marx explains, ‘Use-values must therefore never be treated as the immediate aim of the capitalist; nor must the profit on any single transaction. His aim is rather the unceasing movement of profit-making’ (Marx, 1990: 254).


@RN1423 defined capital both as a process of generating profit and as an object utilized in the process of generating profit. @RN1423 differentiates between _money capital_ -- money invested to make more money -- and _real capital_. Real capital is differentiated into _constant capital_ -- the exchange value of input commodities (e.g., materials, machinery, and facilities) necessary to produce a commodity - and _variable capital_ -- wages paid to labor to produce a commodity.  


What is the source of surplus value for the capitalist? @RN1423 assumes that all commodities exchange at their exchange-value, meaning that the process of buying ($M-C$) and selling ($C-M$) are not the source of profit. Instead, the source of profit in the production of commodities is the exploitation of labor. 

Labor is paid a wage (exchange-value) that is less than the value (use-value) they add to the commodity. This trick is achieved by cloaking the reality of exploitation with the appearance of freedom. @RN1402 states that man owns his own labor and freely consents to exchange his labor for wages. By contrast, @RN1423 argues that man’s only means of subsistence is to sell his labor to capitalists. Therefore, the capitalist coerces labor to accept subsistence wages. Thus, surplus value (profit) is the difference between the (exchange?use?) value created by labor and the wages they are paid.

NOTE: Constant capital is purchased at its exchange-value.

_**Data as capital**_. Bulding on @RN1423, @RN4799 asks, what is the economic form of data? Conceptualizing economic capital as an object used to generate profit, @RN4799 conceives of data as form of capital that is distinct from economic capital, but has roots in economic capital. Furthermore, data can be converted into economic capital in two ways: as raw material (constant capital) and as a product (commodity) of digital labor. First, data can be conceptualized as "digital raw material" -- akin to lumber in construction -- "necessary in the production of commodities" [@RN4799, p. 4]. For example, software that predicts hospital staffing needs depends on historical data about patients. Second, @RN4799 conceptualizes data as a commodity that is 

> produced by the digital labour of people posting on Facebook, clicking on Google, exercising with Fitbits, and all the other things we do that create data and that data is created about. The cliche´ about the ‘free’ services provided digital platforms is that, ‘If you’re not the customer, you’re the product.’1 Through the work of using platforms and devices, people are turned into commodities that take the form of personal data, which is sold to advertisers and data brokers [@RN4799, p. 4].


Organizations approach data collection utilizing the logic of capital accumulation. @RN4799 p. 4 states that "the capitalist is not concerned with the immediate use of a data point or with any single collection, but rather the unceasing flow of data-creating." For example, @RN4799 p. 5 quotes an artificial intelligence researcher who said, "'At large companies, sometimes we launch products not for the revenue, but for the data. We actually do that quite often ... and we monetize the data through a different product'"

@RN4799 argues that data collection is better conceptualized as "data extraction" in order to highlight "the people targeted by, and the exploitative nature" (p. 6) of the process. Much of the data extracted by organizations are data about people (e.g., beliefs, behaviors, personal information). Data extraction typically occurs without "meaningful consent." In order to use a platform, users must sign "consent agreements" that entitle companies to extract, own, and sell data about its users.

Finally, data extraction typically occurs without fair compensation. Often, companies compensate users by allowing users to use the platform. In return, "the owner collects data as payment" [@RN4799, p. 8]. For companies, the exchange "value of data capital is massive. Some of the wealthiest companies in the world, like Facebook and Google, are built on data capital"  [@RN4799, p. 8]. Returning to @RN1423, capitalists generate profit by paying labor less than the value they add to the exchange value of commodities. In platform capitalism, the source of profit is paying users less than the value of the digital labor they provide.

_**Student list data as capital**_. We conceptualize student list data as economic capital, in the sense of an object used to generate profit. Consistent with @RN4799, nearly all student list data is derived from the user-data of students using some product. For example, College Board generates student list data from users of their testing services. Both "Free" college search engines (e.g., Cappex) and also college search software purchased by high schools (e.g., Naviance) created student list data from users looking for colleges and/or scholarships. As a commodity, student list data is a product of the labor of students. For example, student list data sold by College Board is created by the labor of students who fill out pre-test questionnaires about their college preferences and then complete the test. College search software (e.g., Cappex, Naviance) asks students to describe their college preferences and also extracts behavioral data from the efforts of students searching for college using the platform.

Because student list data are a commodity valued by universities looking for customers, the process of profiting from student list data follows follows cycles of money ($M$) and commodities ($C$) observed by @RN1423. A simple real-life  example of $M-C-M'$ is an organization (e.g., Cappex) invests money ($M$) to create a "free" college search engine ($C$) that generates student list data, which is then sold to universities for more money ($M'$). More lucrative approaches generate proprietary student list data as a by-product of money-making products, thereby following an $M-C-M'-C-M''$. For example, College Board invests money ($M$) to create standardized assessments ($C$), which is sold households $M'$ and also extracts student list data ($C$), which are utilized to create the Student Search Service product ($C$), which is sold to universities ($M''$) looking for students. The Naviance (college planning) and Intersect (college recruiting) software platforms -- now owned by PowerSchool -- follow a similar cycle. PowerSchool invests money ($M$) to purchase/maintain Naviance ($C$), which is sold to high school districts ($M'$) and also extracts student list data ($C$), which are utilized to create the Intersect recruiting platform  ($C$), which is sold to universities ($M''$) looking for students.


Finally, @list_biz observed that generating surplus value depends substantially on being an oligopolist supplier, that is extracting proprietary ownership over a large, unique pool of prospective students. For example, in 2011 the online textbook company Chegg tried to enter the student list business. Although Chegg extracted some student list data in-house -- through the acquisition of Zinch -- they were mostly a "lead aggregator," buying student list data from other venders ($M-C$) and reselling these data to universities ($M-C$). @RN1423 argues commodity exchange is not the source of surplus value because commodities are bought and sold at their market exchange-value. Consistent with this argument, the Chegg student list business failed to generate profit because they were paying market price for leads purcahsed from third-party suppliers [CITE].

Whereas vendors historically capitalized by selling student list data at a price-per-prospect to universities, organizations increasingly leverage market power in the supply of student list data to promote software produts and/or consulting services. The most common approach -- exemplified by the PowerSchool's Intersect product and EAB's Enroll360 product -- is to wrap a large pool of proprietary prospects within a software-as-service product designed to target these prospects. Universities that want to recruit these prospects must purchase the software. Similarly, College Board and ACT now leverage their databases of prospective students to promote enrollment management consulting services. Universities that purchases these consulting services gain access to information about prospective students that is not available within purchased student lists (e.g., GIVE EXAMPLE)





# References

<div id="refs"></div>



